<a href="https://colab.research.google.com/github/spiketg/Udacity-Facebook-Private-AI-Scholarship-Challenge/blob/master/Section_2_Federated_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section: Federated Learning

# Lesson: Introducing Federated Learning

Federated Learning is a technique for training Deep Learning models on data to which you do not have access. Basically:

Federated Learning: Instead of bringing all the data to one machine and training a model, we bring the model to the data, train it locally, and merely upload "model updates" to a central server.

Use Cases:

    - app company (Texting prediction app)
    - predictive maintenance (automobiles / industrial engines)
    - wearable medical devices
    - ad blockers / autotomplete in browsers (Firefox/Brave)
    
Challenge Description: data is distributed amongst sources but we cannot aggregated it because of:

    - privacy concerns: legal, user discomfort, competitive dynamics
    - engineering: the bandwidth/storage requirements of aggregating the larger dataset

# Lesson: Introducing / Installing PySyft

In order to perform Federated Learning, we need to be able to use Deep Learning techniques on remote machines. This will require a new set of tools. Specifically, we will use an extensin of PyTorch called PySyft.

### Install PySyft

The easiest way to install the required libraries is with [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/overview.html). Create a new environment, then install the dependencies in that environment. In your terminal:

```bash
conda create -n pysyft python=3
conda activate pysyft # some older version of conda require "source activate pysyft" instead.
conda install jupyter notebook
pip install syft
pip install numpy
```

If you have any errors relating to zstd - run the following (if everything above installed fine then skip this step):

```
pip install --upgrade --force-reinstall zstd
```

and then retry installing syft (pip install syft).

If you are using Windows, I suggest installing [Anaconda and using the Anaconda Prompt](https://docs.anaconda.com/anaconda/user-guide/getting-started/) to work from the command line. 

With this environment activated and in the repo directory, launch Jupyter Notebook:

```bash
jupyter notebook
```

and re-open this notebook on the new Jupyter server.

If any part of this doesn't work for you (or any of the tests fail) - first check the [README](https://github.com/OpenMined/PySyft.git) for installation help and then open a Github Issue or ping the #beginner channel in our slack! [slack.openmined.org](http://slack.openmined.org/)

In [0]:
import torch as th

In [2]:
x = th.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

In [0]:
y = x + x

In [4]:
print(y)

tensor([ 2,  4,  6,  8, 10])


In [6]:
!pip install syft

     |████████████████████████████████| 225kB 2.8MB/s 
     |████████████████████████████████| 389kB 34.2MB/s 
     |████████████████████████████████| 204kB 46.6MB/s 
     |████████████████████████████████| 256kB 33.6MB/s 
     |████████████████████████████████| 460kB 42.0MB/s 
     |████████████████████████████████| 81kB 26.1MB/s 
     |████████████████████████████████| 2.1MB 43.0MB/s 
     |████████████████████████████████| 51kB 8.8MB/s 
     |████████████████████████████████| 266kB 35.0MB/s 
     |████████████████████████████████| 122kB 40.5MB/s 
  Created wheel for zstd: filename=zstd-1.4.1.0-cp36-cp36m-linux_x86_64.whl size=1067072 sha256=a832f0413bf67b3e13beca12c1b7aae2f1d52ccc10b201a26b102765b3f43519
  Stored in directory: /root/.cache/pip/wheels/66/3f/ee/ac08c81af7c1b24a80c746df669ea3cb37542d27877d66ccf4
  Created wheel for pyyaml: filename=PyYAML-5.1.2-cp36-cp36m-linux_x86_64.whl size=44105 sha256=c4a05912f5008f37f907b8eb3ed069a0e04982de2924f045500972e7d41c138e
  Stored in dir

In [7]:
import syft as sy

W0804 23:21:46.359729 140590226450304 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0804 23:21:46.379306 140590226450304 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
hook = sy.TorchHook(th)

In [9]:
th.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

# Lesson: Basic Remote Execution in PySyft

## PySyft => Remote PyTorch

The essence of Federated Learning is the ability to train models in parallel on a wide number of machines. Thus, we need the ability to tell remote machines to execute the operations required for Deep Learning.

Thus, instead of using Torch tensors - we're now going to work with **pointers** to tensors. Let me show you what I mean. First, let's create a "pretend" machine owned by a "pretend" person - we'll call him Bob.

In [0]:
bob = sy.VirtualWorker(hook, id="bob")

In [11]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5])

In [0]:
x = x.send(bob)

In [29]:
bob._objects

{79042379717: tensor([1, 2, 3, 4, 5])}

In [30]:
x.location

<VirtualWorker id:bob #objects:1>

In [31]:
x.id_at_location

79042379717

In [32]:
x.id

72054259489

In [33]:
x.owner

<VirtualWorker id:me #objects:0>

In [34]:
hook.local_worker

<VirtualWorker id:me #objects:0>

In [35]:
x

(Wrapper)>[PointerTensor | me:72054259489 -> bob:79042379717]

In [36]:
x = x.get()
x

tensor([1, 2, 3, 4, 5])

In [37]:
bob._objects

{}

# Project: Playing with Remote Tensors

In this project, I want you to .send() and .get() a tensor to TWO workers by calling .send(bob,alice). This will first require the creation of another VirtualWorker called alice.

In [0]:
# try this project here!

In [0]:
alice = sy.VirtualWorker(hook, id="alice")

In [0]:

x = th.tensor([1,2,3,4,5])


In [0]:
x_ptr = x.send(bob, alice)

In [61]:

x_ptr.get()

[tensor([1, 2, 3, 4, 5]), tensor([1, 2, 3, 4, 5])]

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob, alice)

In [63]:
x.get(sum_results=True)

tensor([ 2,  4,  6,  8, 10])

# Lesson: Introducing Remote Arithmetic

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1]).send(bob)

In [68]:
x

(Wrapper)>[PointerTensor | me:9772552197 -> bob:43680732853]

In [69]:
y

(Wrapper)>[PointerTensor | me:76651506075 -> bob:32947205635]

In [0]:
z = x + y

In [71]:
z

(Wrapper)>[PointerTensor | me:29529125934 -> bob:75847372852]

In [72]:
z = z.get()
z

tensor([2, 3, 4, 5, 6])

In [73]:
z = th.add(x,y)
z

(Wrapper)>[PointerTensor | me:8908326393 -> bob:38996594870]

In [74]:
z = z.get()
z

tensor([2, 3, 4, 5, 6])

In [0]:
x = th.tensor([1.,2,3,4,5], requires_grad=True).send(bob)
y = th.tensor([1.,1,1,1,1], requires_grad=True).send(bob)

In [0]:
z = (x + y).sum()

In [77]:
z.backward()

(Wrapper)>[PointerTensor | me:79461465251 -> bob:52753485608]

In [0]:
x = x.get()

In [79]:
x

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [80]:
x.grad

tensor([1., 1., 1., 1., 1.])

# Project: Learn a Simple Linear Model

In this project, I'd like for you to create a simple linear model which will solve for the following dataset below. You should use only Variables and .backward() to do so (no optimizers or nn.Modules). Furthermore, you must do so with both the data and the model being located on Bob's machine.

In [0]:
# try this project here!

In [0]:
input = th.tensor([[1.,1],[0,1,],[1,0],[0,0]], requires_grad=True).send(bob)
target = th.tensor([[1.],[1],[0],[0]], requires_grad=True).send(bob)

In [0]:
weights = th.tensor([[0.],[0.]], requires_grad=True).send(bob)

In [143]:
for i in range(10):

    pred = input.mm(weights)

    loss = ((pred - target)**2).sum()

    loss.backward()

    weights.data.sub_(weights.grad * 0.1)
    weights.grad *= 0

    print(loss.get().data)


tensor(2.)
tensor(0.5600)
tensor(0.2432)
tensor(0.1372)
tensor(0.0849)
tensor(0.0538)
tensor(0.0344)
tensor(0.0220)
tensor(0.0141)
tensor(0.0090)


# Lesson: Garbage Collection and Common Errors


In [0]:
bob = bob.clear_objects()

In [82]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [84]:
bob._objects

{5179736864: tensor([1, 2, 3, 4, 5])}

In [0]:
del x

In [86]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [88]:
bob._objects

{10020021166: tensor([1, 2, 3, 4, 5])}

In [0]:
x = "asdf"

In [90]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [92]:
x

(Wrapper)>[PointerTensor | me:41245583519 -> bob:89512718740]

In [93]:
bob._objects

{89512718740: tensor([1, 2, 3, 4, 5])}

In [0]:
x = "asdf"

In [95]:
bob._objects

{89512718740: tensor([1, 2, 3, 4, 5])}

In [0]:
del x

In [97]:
bob._objects

{89512718740: tensor([1, 2, 3, 4, 5])}

In [98]:
bob = bob.clear_objects()
bob._objects

{}

In [0]:
for i in range(1000):
    x = th.tensor([1,2,3,4,5]).send(bob)

In [100]:
bob._objects

{30617442809: tensor([1, 2, 3, 4, 5])}

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1])

In [102]:
z = x + y

TensorsNotCollocatedException: ignored

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1]).send(alice)

In [104]:
z = x + y

TensorsNotCollocatedException: ignored

# Lesson: Toy Federated Learning

Let's start by training a toy model the centralized way. This is about a simple as models get. We first need:

- a toy dataset
- a model
- some basic training logic for training a model to fit the data.

In [0]:
from torch import nn, optim

In [0]:
# A Toy Dataset
data = th.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad=True)
target = th.tensor([[1.],[1], [0], [0]], requires_grad=True)

In [0]:
# A Toy Model
model = nn.Linear(2,1)

In [0]:
opt = optim.SGD(params=model.parameters(), lr=0.1)

In [109]:
def train(iterations=20):
    for iter in range(iterations):
        opt.zero_grad()

        pred = model(data)

        loss = ((pred - target)**2).sum()

        loss.backward()

        opt.step()

        print(loss.data)
        
train()

tensor(2.5952)
tensor(0.7144)
tensor(0.3906)
tensor(0.2485)
tensor(0.1616)
tensor(0.1057)
tensor(0.0694)
tensor(0.0457)
tensor(0.0303)
tensor(0.0202)
tensor(0.0135)
tensor(0.0091)
tensor(0.0062)
tensor(0.0042)
tensor(0.0029)
tensor(0.0020)
tensor(0.0014)
tensor(0.0010)
tensor(0.0007)
tensor(0.0005)


In [0]:
data_bob = data[0:2].send(bob)
target_bob = target[0:2].send(bob)

In [0]:
data_alice = data[2:4].send(alice)
target_alice = target[2:4].send(alice)

In [0]:
datasets = [(data_bob, target_bob), (data_alice, target_alice)]

In [0]:
def train(iterations=20):

    model = nn.Linear(2,1)
    opt = optim.SGD(params=model.parameters(), lr=0.1)
    
    for iter in range(iterations):

        for _data, _target in datasets:

            # send model to the data
            model = model.send(_data.location)

            # do normal training
            opt.zero_grad()
            pred = model(_data)
            loss = ((pred - _target)**2).sum()
            loss.backward()
            opt.step()

            # get smarter model back
            model = model.get()

            print(loss.get())

In [114]:
train()

tensor(5.7949, requires_grad=True)
tensor(0.3157, requires_grad=True)
tensor(0.2634, requires_grad=True)
tensor(0.2752, requires_grad=True)
tensor(0.1047, requires_grad=True)
tensor(0.1701, requires_grad=True)
tensor(0.0600, requires_grad=True)
tensor(0.1036, requires_grad=True)
tensor(0.0356, requires_grad=True)
tensor(0.0635, requires_grad=True)
tensor(0.0214, requires_grad=True)
tensor(0.0393, requires_grad=True)
tensor(0.0130, requires_grad=True)
tensor(0.0245, requires_grad=True)
tensor(0.0080, requires_grad=True)
tensor(0.0155, requires_grad=True)
tensor(0.0050, requires_grad=True)
tensor(0.0099, requires_grad=True)
tensor(0.0032, requires_grad=True)
tensor(0.0064, requires_grad=True)
tensor(0.0021, requires_grad=True)
tensor(0.0042, requires_grad=True)
tensor(0.0014, requires_grad=True)
tensor(0.0028, requires_grad=True)
tensor(0.0009, requires_grad=True)
tensor(0.0019, requires_grad=True)
tensor(0.0006, requires_grad=True)
tensor(0.0013, requires_grad=True)
tensor(0.0004, requi

# Lesson: Advanced Remote Execution Tools

In the last section we trained a toy model using Federated Learning. We did this by calling .send() and .get() on our model, sending it to the location of training data, updating it, and then bringing it back. However, at the end of the example we realized that we needed to go a bit further to protect people privacy. Namely, we want to average the gradients BEFORE calling .get(). That way, we won't ever see anyone's exact gradient (thus better protecting their privacy!!!)

But, in order to do this, we need a few more pieces:

- use a pointer to send a Tensor directly to another worker

And in addition, while we're here, we're going to learn about a few more advanced tensor operations as well which will help us both with this example and a few in the future!

In [115]:
bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

<VirtualWorker id:alice #tensors:0>

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
x = x.send(alice)

In [118]:
bob._objects

{50213824318: tensor([1, 2, 3, 4, 5])}

In [120]:
alice._objects

{1234485469: (Wrapper)>[PointerTensor | alice:1234485469 -> bob:50213824318]}

In [0]:
y = x + x

In [122]:
y

(Wrapper)>[PointerTensor | me:68262124958 -> alice:90598298844]

In [123]:
bob._objects

{50213824318: tensor([1, 2, 3, 4, 5]),
 64434302209: tensor([ 2,  4,  6,  8, 10])}

In [124]:
alice._objects

{1234485469: (Wrapper)>[PointerTensor | alice:1234485469 -> bob:50213824318],
 90598298844: (Wrapper)>[PointerTensor | alice:90598298844 -> bob:64434302209]}

In [0]:
jon = sy.VirtualWorker(hook, id="jon")

In [0]:
bob.clear_objects()
alice.clear_objects()

x = th.tensor([1,2,3,4,5]).send(bob).send(alice)

In [127]:
bob._objects

{42316497575: tensor([1, 2, 3, 4, 5])}

In [128]:
alice._objects

{22287085210: (Wrapper)>[PointerTensor | alice:22287085210 -> bob:42316497575]}

In [129]:
x = x.get()
x

(Wrapper)>[PointerTensor | me:22287085210 -> bob:42316497575]

In [130]:
bob._objects

{42316497575: tensor([1, 2, 3, 4, 5])}

In [132]:
alice._objects

{}

In [133]:
x = x.get()
x

tensor([1, 2, 3, 4, 5])

In [134]:
bob._objects

{}

In [0]:
bob.clear_objects()
alice.clear_objects()

x = th.tensor([1,2,3,4,5]).send(bob).send(alice)

In [136]:
bob._objects

{86145408477: tensor([1, 2, 3, 4, 5])}

In [137]:
alice._objects

{88348982: (Wrapper)>[PointerTensor | alice:88348982 -> bob:86145408477]}

In [0]:
del x

In [139]:
bob._objects

{}

In [140]:
alice._objects

{}

# Lesson: Pointer Chain Operations

In [146]:
bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [148]:
bob._objects

{75891767616: tensor([1, 2, 3, 4, 5])}

In [149]:
alice._objects

{}

In [150]:
x.move(alice)

(Wrapper)>[PointerTensor | me:88649509197 -> alice:88649509197]

In [151]:
bob._objects

{}

In [152]:
alice._objects

{88649509197: tensor([1, 2, 3, 4, 5])}

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob).send(alice)

In [154]:
bob._objects

{22321975149: tensor([1, 2, 3, 4, 5])}

In [155]:
alice._objects

{72512886325: (Wrapper)>[PointerTensor | alice:72512886325 -> bob:22321975149],
 88649509197: tensor([1, 2, 3, 4, 5])}

In [156]:
x.remote_get()

(Wrapper)>[PointerTensor | me:14389216376 -> alice:72512886325]

In [157]:
bob._objects

{}

In [158]:
alice._objects

{72512886325: tensor([1, 2, 3, 4, 5]), 88649509197: tensor([1, 2, 3, 4, 5])}

In [159]:
x.move(bob)

(Wrapper)>[PointerTensor | me:14389216376 -> bob:14389216376]

In [160]:
x

(Wrapper)>[PointerTensor | me:14389216376 -> bob:14389216376]

In [161]:
bob._objects

{14389216376: tensor([1, 2, 3, 4, 5])}

In [162]:
alice._objects

{88649509197: tensor([1, 2, 3, 4, 5])}